[tox]
envlist = py310, py311, py312, py313, lint, typecheck
isolated_build = true

[testenv]
passenv = *
deps =
    pytest
    pytest-sugar
    pytest-cov
    python-dotenv
    coverage
    unittest-xml-reporting
    # dependencies for tracking testing
    trackastra
    laptrack
commands =
    coverage run -m pytest --junitxml=report.xml --cov-report term --cov-report xml --cov=acia tests/

[testenv:lint]
basepython = python3.10
deps = ruff
skip_install = true
commands =
    ruff check acia tests
    ruff format --check acia tests

[testenv:typecheck]
basepython = python3.10
deps = mypy
skip_install = true
commands =
    mypy acia --ignore-missing-imports
